name: Secure CI Pipeline

on:
  push:
    branches: ["main"]

jobs:

  security_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ğŸ” scan for leaked secrets
      - name: Secret Scan
        uses: trufflesecurity/trufflehog@main

      # install dependencies
      - name: Install dependencies
        run: npm install

      # ğŸ” check vulnerable packages
      - name: Dependency Scan
        run: npm audit --audit-level=high

  build_scan:
    needs: security_scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # build docker image
      - name: Build Docker Image
        run: docker build -t secure-node-app .

      # ğŸ” scan container vulnerabilities
      - name: Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-node-app
          severity: HIGH,CRITICAL
          exit-code: 1

  test:
    needs: build_scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: npm test